name: .NET


on: [push, pull_request]


jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0'
    - name: Restore dependencies
      run: dotnet restore ST-4.sln
    - name: Build
      run: dotnet build ST-4.sln --no-restore
    - name: Test
      run: dotnet test ST-4.sln --no-build --verbosity normal
